CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Email] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	[Lastname] NVARCHAR(50) NOT NULL,
	[Firstname] NVARCHAR(50) NOT NULL,
	[Birthdate] DATE NOT NULL,
	[NationalRegister] NVARCHAR(50) NOT NULL,
	[Biography] NVARCHAR(120) NOT NULL
)
